<script setup lang="ts">
const props = defineProps<{
  type: 'privacy' | 'terms'
}>()

const emit = defineEmits<{
  close: []
}>()

const isOpen = defineModel<boolean>('modelValue', { default: true })

const handleClose = () => {
  isOpen.value = false
  emit('close')
}
</script>

<template>
  <UModal
    v-model:open="isOpen"
    :ui="{
      content: 'bg-[var(--card-bg)] border border-[var(--border)] rounded-xl max-w-[520px] w-full mx-auto',
      overlay: 'bg-black/60 backdrop-blur-sm'
    }"
    @update:open="(val: boolean) => { if (!val) handleClose() }"
  >
    <div class="legal-content">
      <h2 class="legal-title">{{ type === 'privacy' ? 'Privacy Policy' : 'Terms of Service' }}</h2>
      <div class="legal-scroll">

        <!-- Privacy Policy -->
        <template v-if="type === 'privacy'">
          <p class="legal-updated">Last updated: January 2026</p>

          <h3>1. Information We Collect</h3>
          <p>When you use Recipe Snap, we may collect:</p>
          <ul>
            <li><strong>Account info:</strong> Email address when you sign in via Google, Apple, or magic link.</li>
            <li><strong>Photos:</strong> Images you capture are sent to our AI service for ingredient analysis. We do not store your photos after processing.</li>
            <li><strong>Usage data:</strong> Search history, saved recipes, and credit usage to provide and improve the service.</li>
            <li><strong>Payment info:</strong> Payments are processed by Stripe. We do not store your card details.</li>
          </ul>

          <h3>2. How We Use Your Information</h3>
          <ul>
            <li>To provide recipe suggestions based on your ingredients.</li>
            <li>To sync your saved recipes and settings across devices.</li>
            <li>To process credit purchases and subscriptions.</li>
            <li>To improve the service and fix issues.</li>
          </ul>

          <h3>3. Data Storage</h3>
          <p>Your data is stored securely using Supabase (hosted on AWS). We use industry-standard security measures to protect your information.</p>

          <h3>4. Third-Party Services</h3>
          <p>We use the following third-party services:</p>
          <ul>
            <li><strong>Google Gemini:</strong> For image analysis and recipe generation.</li>
            <li><strong>Supabase:</strong> For authentication and data storage.</li>
            <li><strong>Stripe:</strong> For payment processing.</li>
            <li><strong>Google/Apple Sign-In:</strong> For authentication.</li>
          </ul>

          <h3>5. Data Retention</h3>
          <p>We retain your data for as long as your account is active. You can request deletion of your account and associated data by contacting us at hello@recipesnap.co.</p>

          <h3>6. Your Rights</h3>
          <p>You have the right to:</p>
          <ul>
            <li>Access your personal data.</li>
            <li>Request correction or deletion of your data.</li>
            <li>Export your saved recipes.</li>
            <li>Delete your account at any time.</li>
          </ul>

          <h3>7. Children's Privacy</h3>
          <p>Recipe Snap is not intended for children under 13. We do not knowingly collect personal information from children.</p>

          <h3>8. Changes to This Policy</h3>
          <p>We may update this policy from time to time. We will notify you of significant changes through the app.</p>

          <h3>9. Contact Us</h3>
          <p>If you have questions about this privacy policy, contact us at <a href="mailto:hello@recipesnap.co">hello@recipesnap.co</a>.</p>
        </template>

        <!-- Terms of Service -->
        <template v-else>
          <p class="legal-updated">Last updated: January 2026</p>

          <h3>1. Acceptance of Terms</h3>
          <p>By using Recipe Snap, you agree to these Terms of Service. If you do not agree, please do not use the app.</p>

          <h3>2. Description of Service</h3>
          <p>Recipe Snap is an AI-powered app that analyzes photos of ingredients and suggests recipes. The service is provided "as is" and recipes are generated by AI for inspiration purposes.</p>

          <h3>3. Free and Paid Usage</h3>
          <ul>
            <li>New users receive 10 free snaps without an account.</li>
            <li>After free snaps are used, an account is required.</li>
            <li>Additional snaps can be purchased as credit packs or through a monthly subscription.</li>
            <li>Credit packs are one-time purchases and credits never expire.</li>
            <li>Subscriptions renew monthly and can be canceled anytime through the Stripe Customer Portal.</li>
          </ul>

          <h3>4. Refund Policy</h3>
          <p>Credit pack purchases are non-refundable once credits have been used. For unused credit packs or subscription issues, contact us at <a href="mailto:hello@recipesnap.co">hello@recipesnap.co</a>.</p>

          <h3>5. Subscriptions</h3>
          <ul>
            <li>Subscriptions are billed monthly via Stripe.</li>
            <li>Subscription credits reset each billing cycle and do not accumulate.</li>
            <li>You can cancel your subscription at any time. Access continues until the end of the current billing period.</li>
          </ul>

          <h3>6. Acceptable Use</h3>
          <p>You agree not to misuse the service, including but not limited to:</p>
          <ul>
            <li>Attempting to bypass the credit system.</li>
            <li>Using the service for any unlawful purpose.</li>
            <li>Submitting inappropriate or harmful content.</li>
          </ul>

          <h3>7. AI-Generated Content</h3>
          <p>Recipes are generated by artificial intelligence and are provided for inspiration. We do not guarantee the accuracy, safety, or nutritional information of generated recipes. Always use your own judgment when preparing food, especially regarding allergies and dietary restrictions.</p>

          <h3>8. Limitation of Liability</h3>
          <p>Recipe Snap is not liable for any adverse effects resulting from following AI-generated recipes, including but not limited to allergic reactions, foodborne illness, or nutritional deficiencies.</p>

          <h3>9. Account Termination</h3>
          <p>We reserve the right to suspend or terminate accounts that violate these terms. You may delete your account at any time by contacting us.</p>

          <h3>10. Changes to Terms</h3>
          <p>We may update these terms from time to time. Continued use of the app after changes constitutes acceptance of the updated terms.</p>

          <h3>11. Contact</h3>
          <p>For questions about these terms, contact us at <a href="mailto:hello@recipesnap.co">hello@recipesnap.co</a>.</p>
        </template>

      </div>

      <div class="legal-footer">
        <UButton
          block
          variant="outline"
          color="neutral"
          @click="handleClose"
        >
          Close
        </UButton>
      </div>
    </div>
  </UModal>
</template>

<style scoped>
.legal-content {
  display: flex;
  flex-direction: column;
  max-height: 85vh;
  max-height: 85dvh;
}

.legal-title {
  font-size: 1.15rem;
  font-weight: 600;
  color: var(--text);
  padding: 1.25rem 1.5rem;
  padding-right: 3rem;
  border-bottom: 1px solid var(--border);
  flex-shrink: 0;
}

.legal-scroll {
  flex: 1;
  overflow-y: auto;
  padding: 1.5rem;
  -webkit-overflow-scrolling: touch;
}

.legal-scroll h3 {
  font-size: 0.95rem;
  font-weight: 600;
  color: var(--text);
  margin: 1.5rem 0 0.5rem;
}

.legal-scroll h3:first-of-type {
  margin-top: 0.5rem;
}

.legal-scroll p {
  font-size: 0.88rem;
  line-height: 1.6;
  color: var(--text-light);
  margin-bottom: 0.75rem;
}

.legal-scroll ul {
  margin: 0 0 0.75rem 1.25rem;
  font-size: 0.88rem;
  line-height: 1.6;
  color: var(--text-light);
}

.legal-scroll li {
  margin-bottom: 0.35rem;
}

.legal-scroll a {
  color: var(--primary);
  text-decoration: none;
}

.legal-scroll a:hover {
  text-decoration: underline;
}

.legal-updated {
  font-size: 0.8rem !important;
  color: var(--text-light) !important;
  opacity: 0.7;
  margin-bottom: 1rem !important;
}

.legal-footer {
  padding: 1rem 1.5rem;
  border-top: 1px solid var(--border);
  flex-shrink: 0;
}
</style>
